@{
    RootModule        = 'ImperionPipeline.psm1'
    ModuleVersion     = '0.5.0'
    GUID              = 'b1e7c4a2-6d3f-4f1a-9c2e-7a0d5e8f3b21'
    Author            = 'Mark / Imperion'
    CompanyName       = 'Imperion'
    Description       = 'On-prem ingestion, enrichment, and vectorization engine for ImperionCRM (local pipeline plane).'
    PowerShellVersion = '7.2'

    # Pinned dependencies — see docs/deployment. Not auto-installed at import.
    RequiredModules   = @(
        # @{ ModuleName = 'Microsoft.PowerShell.SecretManagement'; ModuleVersion = '1.1.2' }
        # @{ ModuleName = 'Microsoft.PowerShell.SecretStore';      ModuleVersion = '1.0.6' }
        # @{ ModuleName = 'MSAL.PS';                                ModuleVersion = '4.37.0' }
    )

    FunctionsToExport = @(
        # Runtime / setup
        'Initialize-ImperionContext',
        'Initialize-ImperionUnattended',
        'Register-ImperionTask',
        # Sync cmdlets (scheduled-task entry points)
        'Invoke-ImperionAutotaskContractSync',
        'Invoke-ImperionAutotaskTicketSync',
        # Collector catalog promoted from .task.ps1 -> *Sync cmdlets (epic #286, ADR-0007)
        'Invoke-ImperionAutotaskTimeEntrySync',
        'Invoke-ImperionM365UserSync',
        'Invoke-ImperionM365DeviceSync',
        'Invoke-ImperionDefenderSync',
        'Invoke-ImperionIntuneAppSync',
        'Invoke-ImperionIntuneDeviceSync',
        'Invoke-ImperionEntraAuthMethodSync',
        'Invoke-ImperionCustomSecurityAttributeSync',
        'Invoke-ImperionSensitivityLabelSync',
        'Invoke-ImperionSharePointSiteSync',
        'Invoke-ImperionEntraAppRegistrationSync',
        'Invoke-ImperionEntraDomainSync',
        'Invoke-ImperionEntraGroupMemberSync',
        'Invoke-ImperionEntraGroupSync',
        'Invoke-ImperionEntraRoleAssignmentSync',
        'Invoke-ImperionM365MailSync',
        'Invoke-ImperionM365TeamsChatSync',
        'Invoke-ImperionM365TeamsMeetingSync',
        'Invoke-ImperionScopedInteractionMailSync',
        'Invoke-ImperionScopedInteractionTeamsSync',
        'Invoke-ImperionQboAccountSync',
        'Invoke-ImperionQboBillSync',
        'Invoke-ImperionQboCustomerSync',
        'Invoke-ImperionQboEstimateSync',
        'Invoke-ImperionQboExpenseAccountSync',
        'Invoke-ImperionQboInvoiceSync',
        'Invoke-ImperionQboPaymentSync',
        'Invoke-ImperionQboProfitAndLossSync',
        'Invoke-ImperionQboPurchaseSync',
        'Invoke-ImperionITGlueOrganizationSync',
        'Invoke-ImperionITGlueContactSync',
        'Invoke-ImperionITGlueConfigurationSync',
        'Invoke-ImperionDattoRmmDeviceSync',
        'Invoke-ImperionDattoBcdrBackupSync',
        'Invoke-ImperionCdwOrderSync',
        'Invoke-ImperionAmazonBusinessOrderSync',
        'Invoke-ImperionTelivyReportSync',
        'Invoke-ImperionMileIqDriveSync',
        'Invoke-ImperionMyItProcessRecommendationSync',
        'Invoke-ImperionPlaudRecordingSync',
        'Invoke-ImperionDocuSignEnvelopeSync',
        'Invoke-ImperionDarkWebIdCompromiseSync',
        'Invoke-ImperionEasyDmarcDomainSync',
        'Invoke-ImperionAzureResourceInventorySync',
        'Invoke-ImperionSentinelSync',
        'Invoke-ImperionDnsZoneSync',
        'Invoke-ImperionDnsResolveSync',
        'Invoke-ImperionKqmOpportunitySync',
        'Invoke-ImperionSecurityIncidentSync',
        'Invoke-ImperionMetaSocialSync',
        'Invoke-ImperionMetaInsightSync',
        'Invoke-ImperionServicePrincipalSync',
        'Invoke-ImperionAzureInventorySync',
        'Invoke-ImperionCloudResourceSync',
        'Invoke-ImperionUniFiDeviceSync',
        'Invoke-ImperionSecureScoreSync',
        'Invoke-ImperionPolicySync',
        'Invoke-ImperionPurviewComplianceSync',
        'Invoke-ImperionSecurityRetentionSweep',
        'Invoke-ImperionITGlueExport',
        'Invoke-ImperionKaseyaImport',
        'Invoke-ImperionKnowledgeSync',
        'Invoke-ImperionReceiptLifecycle',
        # Golden state / drift
        'Set-ImperionPolicyGoldenState',
        'Get-ImperionPolicyDrift',
        'Invoke-ImperionPostureMerge',
        'Invoke-ImperionPostureSnapshot',
        'Get-ImperionSecureScore',
        # Semantic-layer (OKF) drift agent (issue #175 / ADR-0086)
        'Get-ImperionSemanticDrift',
        'Invoke-ImperionSemanticDriftSync',
        # Semantic-layer (OKF) bundle vectorizer (issue #176 / ADR-0086 + ADR-0041)
        'Invoke-ImperionSemanticConceptSync',
        # Building blocks (reusable helpers)
        'Invoke-ImperionM365EstateSweep',
        'Write-ImperionLog',
        'Get-ImperionContentHash',
        'ConvertTo-ImperionFlatObject',
        'Join-ImperionValues',
        'Connect-ImperionSecretStore',
        'Get-ImperionAccessToken',
        'Open-ImperionDbConnection',
        'Invoke-ImperionDbQuery',
        'Invoke-ImperionDbNonQuery',
        'Invoke-ImperionBronzeUpsert',
        'Invoke-ImperionGraphRequest',
        'Invoke-ImperionArmRequest',
        'Remove-ImperionStorageBlob',
        'Get-ImperionKeyVaultSecret',
        'Invoke-ImperionITGlueRequest',
        'Set-ImperionITGlueFlexibleAsset',
        # Per-API connect layer (reusable connection / paged-request utilities)
        'Get-ImperionAutotaskZone',
        'Invoke-ImperionAutotaskRequest',
        'Invoke-ImperionTelivyRequest',
        'Invoke-ImperionDarkWebIdRequest',
        'Invoke-ImperionDocuSignRequest',
        'Invoke-ImperionUniFiRequest',
        'Invoke-ImperionPlaudRequest',
        'Invoke-ImperionKqmRequest',
        'Invoke-ImperionEasyDmarcRequest',
        'Invoke-ImperionQboRequest',
        'Invoke-ImperionMileIqRequest',
        'Invoke-ImperionMetaRequest',
        'Get-ImperionMetaPageToken',
        'Invoke-ImperionDattoRmmRequest',
        'Invoke-ImperionDattoBcdrRequest',
        'Invoke-ImperionMyItProcessRequest',
        'Invoke-ImperionAmazonBusinessRequest',
        'Invoke-ImperionCdwRequest',
        # Per-object get layer (collect -> flatten to PSObject; no writes)
        'Get-ImperionAutotaskCompany',
        'Get-ImperionAutotaskContact',
        'Get-ImperionAutotaskContract',
        'Get-ImperionAutotaskTicket',
        'Get-ImperionAutotaskTimeEntry',
        'Get-ImperionM365User',
        'Get-ImperionM365Device',
        'Get-ImperionIntuneManagedApp',
        'Get-ImperionM365Mail',
        'Get-ImperionM365TeamsChat',
        'Get-ImperionM365TeamsMeeting',
        'Get-ImperionScopedInteractionMail',
        'Get-ImperionScopedInteractionTeams',
        'Get-ImperionAzureSubscription',
        'Get-ImperionAzureResourceGroup',
        'Get-ImperionAzureResource',
        'Get-ImperionCloudResource',
        'Get-ImperionDnsZoneObject',
        'Get-ImperionDnsResolveObject',
        'Get-ImperionSentinelObject',
        'Get-ImperionDefenderObject',
        'Get-ImperionEntraAuthMethod',
        'Get-ImperionEntraDomain',
        'Get-ImperionEntraAppRegistration',
        'Get-ImperionEntraRoleAssignment',
        'Get-ImperionSensitivityLabel',
        'Get-ImperionCustomSecurityAttribute',
        'Get-ImperionSharePointSite',
        'Get-ImperionM365Group',
        'Get-ImperionM365GroupMember',
        'Get-ImperionITGlueOrganization',
        'Get-ImperionITGlueContact',
        'Get-ImperionITGlueConfiguration',
        'Get-ImperionTelivyReport',
        'Get-ImperionDarkWebIdCompromise',
        'Get-ImperionDocuSignEnvelope',
        'Get-ImperionUniFiDevice',
        'Get-ImperionPlaudRecording',
        'Get-ImperionKqmOpportunity',
        'Get-ImperionKqmOpportunityDetail',
        'Get-ImperionKqmFieldName',
        'Get-ImperionEasyDmarcDomain',
        'Get-ImperionQboPurchase',
        'Get-ImperionQboExpenseAccount',
        'Get-ImperionQboInvoice',
        'Get-ImperionQboPayment',
        'Get-ImperionQboCustomer',
        'Get-ImperionQboEstimate',
        'Get-ImperionQboBill',
        'Get-ImperionQboAccount',
        'Get-ImperionQboProfitAndLoss',
        'Get-ImperionMileIqDrive',
        'Get-ImperionMetaPagePost',
        'Get-ImperionMetaPostComment',
        'Get-ImperionMetaConversation',
        'Get-ImperionInstagramMedia',
        'Get-ImperionInstagramComment',
        'Get-ImperionMetaInsight',
        'Get-ImperionSecurityIncident',
        'Get-ImperionDattoRmmDevice',
        'Get-ImperionDattoBcdrBackup',
        'Get-ImperionMyItProcessRecommendation',
        'Get-ImperionAmazonBusinessOrder',
        'Get-ImperionCdwOrder',
        # Per-object post layer (write flattened rows -> bronze; change-detected upsert)
        'Set-ImperionAutotaskContractToBronze',
        'Set-ImperionAutotaskTicketToBronze',
        'Set-ImperionAutotaskTimeEntryToBronze',
        'Set-ImperionTelivyReportToBronze',
        'Set-ImperionDarkWebIdCompromiseToBronze',
        'Set-ImperionDocuSignContractToBronze',
        'Set-ImperionUniFiDeviceToBronze',
        'Set-ImperionPlaudRecordingToBronze',
        'Set-ImperionKqmOpportunityToBronze',
        'Set-ImperionKqmOpportunityDetailToBronze',
        'Set-ImperionEasyDmarcDomainToBronze',
        'Set-ImperionQboPurchaseToBronze',
        'Set-ImperionQboExpenseAccountToBronze',
        'Set-ImperionQboInvoiceToBronze',
        'Set-ImperionQboPaymentToBronze',
        'Set-ImperionQboCustomerToBronze',
        'Set-ImperionQboEstimateToBronze',
        'Set-ImperionQboBillToBronze',
        'Set-ImperionQboAccountToBronze',
        'Set-ImperionQboProfitAndLossToBronze',
        'Set-ImperionMileIqDriveToBronze',
        'Set-ImperionM365UserToBronze',
        'Set-ImperionM365DeviceToBronze',
        'Set-ImperionM365MailToBronze',
        'Set-ImperionM365TeamsChatToBronze',
        'Set-ImperionM365TeamsMeetingToBronze',
        'Set-ImperionScopedInteractionMailToBronze',
        'Set-ImperionScopedInteractionTeamsToBronze',
        'Set-ImperionIntuneManagedDeviceToBronze',
        'Set-ImperionIntuneManagedAppToBronze',
        'Set-ImperionITGlueOrganizationToBronze',
        'Set-ImperionITGlueContactToBronze',
        'Set-ImperionITGlueConfigurationToBronze',
        'Set-ImperionAzureSubscriptionToBronze',
        'Set-ImperionAzureResourceGroupToBronze',
        'Set-ImperionAzureResourceToBronze',
        'Set-ImperionCloudResourceToBronze',
        'Set-ImperionDnsZoneToBronze',
        'Set-ImperionDnsRecordToBronze',
        'Set-ImperionDnsGoldenState',
        'Get-ImperionDnsDrift',
        'Invoke-ImperionDnsMerge',
        'Invoke-ImperionCloudAssetMerge',
        'Set-ImperionSentinelToBronze',
        'Set-ImperionDefenderToBronze',
        'Set-ImperionEntraAuthMethodToBronze',
        'Set-ImperionEntraDomainToBronze',
        'Set-ImperionEntraAppRegistrationToBronze',
        'Set-ImperionEntraRoleAssignmentToBronze',
        'Set-ImperionSensitivityLabelToBronze',
        'Set-ImperionCustomSecurityAttributeToBronze',
        'Set-ImperionSharePointSiteToBronze',
        'Set-ImperionM365GroupToBronze',
        'Set-ImperionM365GroupMemberToBronze',
        'Set-ImperionMetaPostToBronze',
        'Set-ImperionMetaCommentToBronze',
        'Set-ImperionMetaMessageToBronze',
        'Set-ImperionInstagramMediaToBronze',
        'Set-ImperionInstagramCommentToBronze',
        'Set-ImperionMetaInsightToBronze',
        'Set-ImperionSecurityIncidentToBronze',
        'Set-ImperionDattoRmmDeviceToBronze',
        'Set-ImperionDattoBcdrBackupToBronze',
        'Set-ImperionMyItProcessRecommendationToBronze',
        'Set-ImperionAmazonBusinessOrderToBronze',
        'Set-ImperionCdwOrderToBronze',
        'Invoke-ImperionMetaMerge',
        'Invoke-ImperionM365DirectoryMerge',
        'Invoke-ImperionITGlueExportToBronze',
        # Gold knowledge + vectorization (ADR-0009; front-end migration 0045)
        # Lever A (issue #226 / ADR surface-shrink): the per-entity knowledge
        # composers (Get-ImperionKnowledge*), the gold writer (Set-ImperionKnowledgeObject),
        # the chunker (Split-ImperionTextChunk), and the Voyage client
        # (Get-ImperionVoyageEmbedding) are internal building blocks of the two
        # orchestrators below — they are now Private (src/.../Private/knowledge/) and
        # remain callable in-module. Only the two genuine entrypoints stay exported.
        'Invoke-ImperionKnowledgeSync',
        'Invoke-ImperionVectorizeKnowledge'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}
